README.md
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/meta/main.yml
tests/integration/targets/clickhouse_info/tasks/initial.yml
tests/integration/targets/clickhouse_info/tasks/main.yml

clickhouse_info: Add the module

clickhouse_info: Add the module

---

README.md
changelogs/fragments/1-clickhouse_info.yml
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/tasks/initial.yml

clickhouse_info: add features

---

plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/tasks/initial.yml

clickhouse_info: add clusters ret value

clickhouse_info: add clusters ret value

---

plugins/modules/clickhouse_info.py

For older versions, scripts crashed with errors. This PR fixes version compatibility
- Bugfix Pull Request

Fix to support different versions

---

CHANGELOG.rst
changelogs/changelog.yaml
galaxy.yml

Release 0.1.1 commit

---

changelogs/fragments/0-clickhouse_info_limit.yml
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/tasks/initial.yml

clickhouse_info: add limit argument

clickhouse_info: add limit argument

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0-clickhouse_info_limit.yml
galaxy.yml

Release 0.2.0 commit

---

changelogs/fragments/0-clickhouse_info.yml
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/tasks/initial.yml
tests/integration/targets/setup_clickhouse/files/test_dictionary.xml
tests/integration/targets/setup_clickhouse/tasks/install.yml

Added the collection of information on tables, dictionaries and merge_tree_settings

Added the collection of information on tables, dictionaries and settings

---

plugins/modules/clickhouse_db.py

clickhouse_db.py: improve examples

clickhouse_db.py: improve examples

---

changelogs/fragments/1-clickhouse_client.yml
changelogs/fragments/2-clickhouse_client.yml
plugins/modules/clickhouse_client.py
tests/integration/targets/clickhouse_client/tasks/initial.yml

Relates to https://github.com/ansible-collections/community.clickhouse/issues/32
clickhouse_client: Add ip types support

clickhouse_client: Add ip types support

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0-clickhouse_info.yml
changelogs/fragments/1-clickhouse_client.yml
changelogs/fragments/2-clickhouse_client.yml
galaxy.yml

Release v0.3.0 commit

---

.github/workflows/ansible-test-plugins.yml

GHA matrix: uncomment all supported ansible-core versions

GHA matrix: uncomment all supported ansible-core versions

---

changelogs/fragments/0-clickhouse_info.yml
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/tasks/initial.yml

Added the collection of information on quotas and settings_profiles

Added the collection of information settings_profiles, quotas

---

CONTRIBUTING.md

CONTRIBUTING.md: add guidelines
@aleksvagachev i'd recommend to refer to the "Reviewing open issue and pull requests" section when reviewing not mine PRs in future:) Those things are very important

CONTRIBUTING.md: add guidelines

---

changelogs/fragments/1-clickhouse_db.yml
plugins/module_utils/clickhouse.py
plugins/modules/clickhouse_db.py
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_db/tasks/initial.yml

clickhouse_db: add comment argument

clickhouse_db: add comment argument

---

changelogs/fragments/2-clickhouse_db.yml
plugins/modules/clickhouse_db.py
tests/integration/targets/clickhouse_db/tasks/initial.yml

- Added the ability to rename databases
- Added the ability to execute commands on all cluster hosts

Renaming databases

---

changelogs/fragments/2-clickhouse_info.yml
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/tasks/initial.yml

Added the collection of information on functions

Added the collection of information functions

---

plugins/modules/clickhouse_user.py
tests/integration/targets/clickhouse_user/tasks/initial.yml

Fixes https://github.com/ansible-collections/community.clickhouse/issues/50

clickhouse_user: add update_password argument

---

changelogs/fragments/3-clickhouse_info.yml
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/tasks/initial.yml

Added the collection of information storage_policies

Added the collection of information storage_policies

---

plugins/modules/clickhouse_user.py
tests/integration/targets/clickhouse_user/tasks/initial.yml

Added no_log=False for type/update password
Removes warning messages
- Bugfix Pull Request

Added no_log=False for type/update password

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0-clickhouse_info.yml
changelogs/fragments/1-clickhouse_db.yml
changelogs/fragments/2-clickhouse_db.yml
changelogs/fragments/2-clickhouse_info.yml
changelogs/fragments/3-clickhouse_info.yml
galaxy.yml

Release v0.4.0 commit

---

changelogs/fragments/0-clickhouse_user.yml
plugins/modules/clickhouse_user.py
tests/integration/targets/clickhouse_user/tasks/initial.yml

Added the ability to add settings with their restrictions applied by default when a user logs in.

New feature when creating a user

---

plugins/modules/clickhouse_role.py
tests/integration/inventory
tests/integration/targets/clickhouse_role/meta/main.yml
tests/integration/targets/clickhouse_role/tasks/initial.yml
tests/integration/targets/clickhouse_role/tasks/main.yml

Resolves #48 
- New Module Pull Request
MVP clickhouse role
N/A

MVP for the clickhouse module

---

plugins/modules/clickhouse_role.py
plugins/modules/clickhouse_user.py
tests/integration/targets/clickhouse_role/tasks/initial.yml

Added new role management features

Added new role management features

---

changelogs/fragments/1-client.yml
plugins/doc_fragments/client_inst_opts.py
plugins/modules/clickhouse_client.py
tests/integration/targets/clickhouse_client/tasks/initial.yml
tests/unit/plugins/module_utils/test_clickhouse.py

Relates to https://github.com/ansible-collections/community.clickhouse/pull/63

Fix unit tests, add a changelog fragment, make formatting consistent

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0-clickhouse_user.yml
changelogs/fragments/1-clickhouse_client.yml
galaxy.yml

Release 0.5.0 commit

---

changelogs/fragments/0-clickhouse_info.yml
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/tasks/initial.yml

clickhouse_info: add roles info per user

clickhouse_info: add roles info per user

---

changelogs/fragments/0-info_add_grants.yml
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/tasks/initial.yml

clickhouse_info: add grants field for roles and users return vals

clickhouse_info: add grants field for roles and users return vals

---

changelogs/fragments/1-info_add_all_grants.yml
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/tasks/initial.yml

Added collection of all grants for users and roles

Added grants for clickhouse_info

---

meta/ee-bindep.txt
meta/ee-requirements.txt
meta/execution-environment.yml

Change Getting started EE guide reference to point to the relevant location

Change Getting started EE guide reference to point to the relevant location

---

changelogs/fragments/2-info_add_all_settings_profiles.yml
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/tasks/initial.yml

Added collection of all settings of roles, users and profiles.

Add settings_profile_elements

---

.github/workflows/ansible-test-plugins.yml

GHA: add stable-2.18, remove stable-2.15

GHA: add stable-2.18, remove stable-2.15

---

README.md

README: improve

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0-info_add_grants.yml
changelogs/fragments/1-info_add_all_grants.yml
changelogs/fragments/2-info_add_all_settings_profiles.yml
changelogs/fragments/3-info_get_functions.yml
galaxy.yml

Release 0.7.0 commit

---

changelogs/config.yaml
galaxy.yml

Fix linting error, adjusting changelog config

Fix linting error, adjusting changelog config

---

.github/workflows/ansible-test-plugins.yml
tests/integration/targets/clickhouse_info/tasks/initial.yml
tests/integration/targets/setup_clickhouse/files/cluster.xml
tests/integration/targets/setup_clickhouse/tasks/install.yml
tests/integration/targets/setup_clickhouse/vars/main.yml

Solution to issue #89
- Added testing of version 24.8.6.70
- Fixed integration tests

Fixed integration tests

---

.github/workflows/ansible-test-plugins.yml
changelogs/fragments/0-clickhouse_info.yml
plugins/modules/clickhouse_info.py
tests/integration/targets/clickhouse_info/tasks/initial.yml

- Added support for version 23
- Versions 21 and 22 are not supported.

Added support for version 23

---

README.md

Fix  the CI status badge in README.md

Fix  the CI status badge in README.md

---

plugins/modules/clickhouse_client.py

clickhouse_info: update examples by replacing getting server version with something else as now we should to it using  the `clickhouse_info` module

clickhouse_info: update examples

---

changelogs/fragments/0-clickhouse_user.yml
plugins/modules/clickhouse_user.py
tests/integration/targets/clickhouse_user/tasks/initial.yml
tests/integration/targets/setup_clickhouse/vars/main.yml

Fixes https://github.com/ansible-collections/community.clickhouse/issues/97
Reproduced, see the tests

clickhouse_user: fix granting roles when creating a user

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0-clickhouse_info.yml
changelogs/fragments/0-clickhouse_user.yml
galaxy.yml

Release 0.8.0 commit

---

CHANGELOG.rst
changelogs/changelog.yaml
galaxy.yml

Release 0.8.1 commit

---

CHANGELOG.rst
changelogs/fragments/105-clickhouse_user.yaml
plugins/modules/clickhouse_user.py

Add `ON CLUSTER` clause to all update user functions
Fixes #104 
- Bugfix Pull Request
clickhouse_user

Fix user password update

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/105-clickhouse_user.yaml
galaxy.yml

Release 0.8.2 commit

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/107-clickhouse_db.yaml
galaxy.yml

Release 0.8.3 commit

---

.github/workflows/ansible-test-plugins.yml

Fixes https://github.com/ansible-collections/community.clickhouse/issues/112

CI: copy ignore-2.19.txt to ignore-2.20.txt

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0-client.yml
galaxy.yml

Release 0.8.5 commit

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0-user_update_settings.yml
changelogs/fragments/1-user_quote_names.yml
galaxy.yml

Release 0.10.0 commit
